<?php
/**
 * Local service-area content and shared city-page renderer.
 */
function highend_service_city_data() {
	return array(
		'edmonton' => array(
			'city' => 'Edmonton',
			'intro' => 'HighEnd Blinds is based in Edmonton, where we measure, manufacture, and install custom window coverings for houses, condos, offices, clinics, and retail spaces. Working locally keeps communication direct and lets our team manage each project from the first fabric comparison through the final installation and adjustment.',
			'local' => 'Edmonton homes face bright summer evenings, early sunrises, winter glare, and significant seasonal temperature changes. South- and west-facing rooms often benefit from sunscreen or light-filtering fabrics, while bedrooms may need blackout roller blinds. Tall stairwell windows and open-to-above living rooms are excellent candidates for rechargeable motorized blinds or Dream Curtains.',
			'fit' => 'From established neighbourhood homes to downtown condos and new suburban builds, Edmonton windows vary widely in depth, width, trim, and access. We check mounting space, handles, tile, casing, and furniture placement before recommending an inside mount, outside mount, cassette, side channel, or motorized solution.',
			'products' => "As the city where we design and manufacture every order, Edmonton customers see the widest range of options in person: zebra blinds for adjustable light and privacy, roller blinds in light-filtering, sunscreen, privacy, and blackout fabrics, motorized blinds for cordless operation, and motorized Dream Curtains for family rooms, open-to-above spaces, and patio doors — light filtering with privacy, not a blackout product. Whether you prefer a simple wand, a chain with a safety guard, or a rechargeable motor controlled by remote, app, schedule, or smart-home hub, we'll walk you through the real trade-offs rather than defaulting to the most expensive option.",
			'process' => 'Because our workshop is right here in Edmonton, your free in-home consultation is often followed by one of the shortest lead times we offer. We measure width, height, depth, squareness, obstacles, and mounting conditions on-site, then manufacture the order at our own facility rather than routing it through a distant supplier. Installation includes mounting and levelling the hardware, checking clearances, testing every blind, and programming anything motorized, with a full walkthrough of operation and care before we leave.',
			'commercial' => 'From single condo windows to multi-unit residential buildings, downtown offices, and retail storefronts, we treat every Edmonton project with the same measurement discipline. Larger commercial orders benefit from matched fabric lots, consistent hardware finishes, and coordinated installation scheduling so tenants or staff see minimal disruption.',
			'care' => 'We encourage Edmonton customers to view fabric samples in both direct window light and the softer light deeper in the room, since colour and openness can look different in each. Before we finalize an order we talk through cleaning needs, day-versus-night privacy, room-darkening goals, and how nearby doors or furniture might affect daily operation. Ongoing care is simple: light dusting with a soft brush or vacuum attachment, a careful damp-cloth wipe for most roller fabrics, spot-cleaning only for zebra and curtain fabrics, and periodic recharging for anything motorized.',
		),
		'sherwood-park' => array(
			'city' => 'Sherwood Park',
			'intro' => 'HighEnd Blinds provides free in-home consultations and professional installation throughout Sherwood Park. We bring fabric and control samples to your home or business, measure every opening, manufacture the order locally in Edmonton, and return with the hardware and programming required for a clean finished installation.',
			'local' => 'Sherwood Park includes mature homes, renovated properties, acreages, townhomes, and newer developments with large expanses of glass. Privacy needs can change from a front-facing room to a backyard window, so we help select the right combination of zebra, sunscreen, light-filtering, blackout, or motorized blinds for each exposure.',
			'fit' => 'Wide living-room windows and patio doors need careful planning for tube strength, fabric roll direction, stack space, and everyday access. Dream Curtains provide soft daylight and walk-through convenience at patio doors, while grouped motorized roller or zebra blinds can make several windows operate together from one remote or app.',
			'products' => "For Sherwood Park's mix of mature homes, renovated properties, and newer builds with large expanses of glass, we bring the full lineup to your consultation: zebra blinds for adjustable privacy, roller blinds in blackout, sunscreen, light-filtering, or privacy fabrics, motorized blinds for cordless control, and motorized Dream Curtains for patio doors and open-to-above rooms — a light-filtering product, not blackout. Operating options run from a simple wand or safety-guarded chain up to rechargeable motors controlled by remote, app, schedule, or smart-home hub, matched to how each room is actually used.",
			'process' => 'Your consultation happens in your Sherwood Park home, with fabric and control samples on hand so you can compare against your own flooring and light. We measure every opening for width, height, depth, and mounting conditions, then manufacture the order at our Edmonton facility rather than through a third-party supplier. On installation day we mount and level the hardware, check clearances, test every blind, and program anything motorized, walking you through operation before we go.',
			'commercial' => 'Sherwood Park brings a genuine mix of homeowners, landlords, and small businesses, and we size our process to the project rather than the other way around — a single acreage window gets the same careful measurement as a coordinated multi-window townhome order or a small commercial fit-out, with matched fabric lots and consistent hardware when a project calls for it.',
			'care' => "Because privacy needs in Sherwood Park often differ between a front-facing room and a backyard-facing one, we encourage viewing samples in both direct and indirect light before deciding. We'll cover cleaning expectations, day-and-night privacy, and how furniture or doors near the window might affect daily use. Maintenance stays simple afterward: soft dusting or a vacuum attachment, careful damp-cloth wiping for most roller fabrics, spot-cleaning only for zebra and curtain fabrics, and periodic recharging for motorized units.",
		),
		'st-albert' => array(
			'city' => 'St. Albert',
			'intro' => 'HighEnd Blinds measures and installs custom blinds and motorized window coverings across St. Albert. Our Edmonton manufacturing team builds each order to the measurements taken in your space, helping reduce delays and giving customers local support for installation, programming, warranty questions, and future adjustments.',
			'local' => 'St. Albert properties range from character homes and renovated interiors to contemporary new builds with tall ceilings and oversized windows. We consider privacy from nearby streets and paths, room orientation, decorative style, and the way each room is used before recommending a fabric or operating system.',
			'fit' => 'Zebra blinds work well where adjustable daylight and privacy are both important. Roller blinds offer a minimal profile with sunscreen, light-filtering, privacy, or blackout fabrics. For high windows, nurseries, primary bedrooms, and whole-room groups, rechargeable motorization removes hanging controls and simplifies daily operation.',
			'products' => "St. Albert's character homes and contemporary new builds call for different answers depending on the window, so we bring zebra blinds, roller blinds in light-filtering, sunscreen, privacy, and blackout fabrics, motorized blinds, and motorized Dream Curtains to every consultation. Dream Curtains soften daylight and add privacy at patio doors and tall open spaces without blacking the room out. You can operate any of these with a wand, a safety-guarded chain, or a rechargeable motor run by remote, app, schedule, or smart-home hub.",
			'process' => 'We start with a free consultation inside your St. Albert home, comparing fabric and hardware samples against your existing finishes. Every opening is measured for width, height, depth, squareness, and mounting conditions before we manufacture the order at our own Edmonton facility. Installation includes levelling and mounting the hardware, checking clearances, testing each blind, and programming motorized products, with a full explanation of care and operation before we leave.',
			'commercial' => "St. Albert's renovated character homes, new builds, and the occasional small business all get the same measurement-first approach. A single-room renovation project is treated with the same care as a full-house order or a coordinated commercial installation, with matched fabric lots and consistent hardware wherever a project spans multiple windows.",
			'care' => 'Given how close some St. Albert homes sit to streets and walking paths, we recommend viewing samples in both bright window light and the room\'s ambient light before choosing a fabric. We\'ll walk through cleaning needs, privacy expectations day and night, and how nearby furniture or doors affect use. Afterward, care is straightforward — light dusting or a vacuum attachment, damp-cloth wiping for most roller fabrics, spot-cleaning only for zebra and curtain fabrics, and periodic recharging for motorized units.',
		),
		'beaumont' => array(
			'city' => 'Beaumont',
			'intro' => 'HighEnd Blinds serves Beaumont with in-home product guidance, accurate window measurement, local manufacturing, and professional installation. We work with homeowners during new construction, after possession, and during renovations to create window coverings that fit the room instead of relying on standard retail sizes.',
			'local' => 'Many Beaumont homes feature open main floors, patio doors, bonus rooms, and tall open-to-above spaces. These designs look beautiful but often need different window treatments within the same home. We can coordinate fabrics and cassette colours while matching privacy and light control to the practical needs of each room.',
			'fit' => 'Motorized blinds are particularly useful for high foyer and stairwell windows. Blackout roller fabrics suit bedrooms and media rooms, sunscreen fabrics reduce glare in bright gathering spaces, and motorized Dream Curtains offer light filtering with privacy for patio doors and family rooms. Dream Curtains are not a blackout product.',
			'products' => "Beaumont's open main floors and tall open-to-above spaces are exactly where our full product range earns its keep: zebra blinds for adjustable privacy, roller blinds in blackout, sunscreen, light-filtering, or privacy fabrics, motorized blinds for cordless operation, and motorized Dream Curtains for patio doors and family rooms — light filtering with privacy, not a blackout product. Choose a simple wand, a safety-guarded chain, or a rechargeable motor controlled by remote, app, schedule, or smart-home hub, depending on how reachable and how often each window is used.",
			'process' => "Whether you're finishing new construction, settling in after possession, or mid-renovation, your Beaumont consultation happens on-site so you can compare samples against your actual flooring and light. We measure every window for width, height, depth, and mounting conditions, then manufacture the order at our Edmonton facility instead of a distant supplier. Installation covers mounting, levelling, clearance checks, testing, and motor programming, with a full walkthrough before we leave.",
			'commercial' => "Beaumont's newer builds mean we regularly coordinate whole-house orders during construction or shortly after possession, alongside smaller single-room projects. Either way, larger orders get matched fabric lots, consistent hardware, and a planned installation sequence so every room looks and operates consistently.",
			'care' => "Because Beaumont's open floor plans often mean one fabric choice is visible from several rooms at once, we recommend viewing samples in both direct and ambient light before deciding. We'll go over cleaning needs, day-and-night privacy, room-darkening goals, and clearance around patio doors or bonus-room furniture. Ongoing care stays simple: light dusting or a vacuum attachment, damp-cloth wiping for most roller fabrics, spot-cleaning only for zebra and curtain fabrics, and periodic recharging for motorized units.",
		),
		'leduc' => array(
			'city' => 'Leduc',
			'intro' => 'HighEnd Blinds supplies custom zebra blinds, roller shades, motorized blinds, and Dream Curtains throughout Leduc. Your consultation takes place in the room where the product will be used, making it easier to compare fabric colour, transparency, privacy, and operation under the home’s actual lighting conditions.',
			'local' => 'Leduc homeowners often need a practical mix: privacy at front-facing windows, glare reduction in living spaces, darkness in bedrooms, and easy access at patio doors. Instead of forcing one fabric throughout the house, we coordinate complementary products that solve the needs of each room while maintaining a consistent look.',
			'fit' => 'Our team checks window depth, casing, handles, sill clearance, and nearby doors before production. That measurement process is especially important for wide roller shades, shallow frames, grouped zebra blinds, and motorized systems. Each finished order is made locally, installed professionally, tested, and explained before we leave.',
			'products' => 'Leduc homeowners usually need a practical mix rather than one fabric throughout — zebra blinds for adjustable front-window privacy, roller blinds in sunscreen, light-filtering, privacy, or blackout fabrics for living spaces and bedrooms, motorized blinds for cordless convenience, and motorized Dream Curtains at patio doors for soft daylight and walk-through privacy. Operating choices span a simple wand or safety-guarded chain up to a rechargeable motor with remote, app, schedule, or smart-home control.',
			'process' => 'Your consultation takes place in the Leduc room where the product will actually be used, so you can judge fabric colour and transparency under real lighting. We measure window depth, casing, handles, and sill clearance before production, then manufacture each order at our Edmonton facility. On install day we mount and level hardware, check clearances, test every blind, and program motorized units, explaining care and operation before we go.',
			'commercial' => 'We coordinate complementary products room by room for Leduc homeowners rather than forcing one fabric throughout the house, and we apply that same room-by-room discipline to larger residential or small commercial orders — matching fabric lots and hardware so a multi-window project looks and operates as one coordinated system.',
			'care' => 'Since Leduc homes often mix privacy, glare, darkness, and access needs across just a few rooms, we recommend comparing samples in both bright and ambient light before settling on a fabric. We\'ll cover cleaning expectations, privacy day and night, and clearance at patio doors before you approve the order. Afterward, care is simple: soft dusting or a vacuum attachment, damp-cloth wiping for most roller fabrics, spot-cleaning only for zebra and curtain fabrics, and periodic recharging for motorized units.',
		),
		'spruce-grove' => array(
			'city' => 'Spruce Grove',
			'intro' => 'HighEnd Blinds offers free consultations and professional blind installation in Spruce Grove. We bring samples to your property, help narrow the choices, record exact measurements, manufacture the selected window coverings in Edmonton, and install the finished order with local warranty and adjustment support.',
			'local' => 'Spruce Grove homes include established neighbourhood properties, townhomes, acreages, and newer houses with open layouts and large windows. Window direction and surrounding sightlines affect the best choice, so we evaluate daytime glare, evening privacy, furniture placement, and how often each blind will be operated.',
			'fit' => 'Sunscreen rollers can preserve an outdoor view while reducing glare, zebra blinds make privacy adjustable, and blackout roller fabrics are designed for sleeping spaces. Rechargeable motors are a clean option for grouped windows and difficult locations because they need no new electrical wiring and eliminate loose operating chains.',
			'products' => "Spruce Grove's mix of established homes, townhomes, and newer open-layout builds calls for different fabrics room to room, so we bring zebra blinds, roller blinds in sunscreen, light-filtering, privacy, and blackout options, motorized blinds, and motorized Dream Curtains to every consultation. Dream Curtains add soft daylight and privacy at patio doors and large windows without blacking the room out. Operate any of these by wand, safety-guarded chain, or rechargeable motor with remote, app, schedule, or smart-home control.",
			'process' => 'We bring samples directly to your Spruce Grove property so you can compare them against your own light and finishes, then record exact measurements for width, height, depth, and mounting conditions. Every order is manufactured at our Edmonton facility rather than through a third-party supplier, and installation includes mounting, levelling, clearance checks, testing, and motor programming, with local warranty and adjustment support afterward.',
			'commercial' => "Whether it's a single large window in a newer Spruce Grove build or a coordinated order across an established-neighbourhood home or townhome complex, we apply the same measurement-first process — with matched fabric lots and consistent hardware whenever a project spans multiple openings.",
			'care' => "Because window direction and nearby sightlines vary so much across Spruce Grove's older and newer homes, we recommend viewing samples in both daytime glare and the room's ambient light before choosing. We'll discuss cleaning needs, evening privacy, and how often each blind will realistically be operated. Maintenance afterward is straightforward: light dusting or a vacuum attachment, damp-cloth wiping for most roller fabrics, spot-cleaning only for zebra and curtain fabrics, and periodic recharging for motorized units.",
		),
		'fort-saskatchewan' => array(
			'city' => 'Fort Saskatchewan',
			'intro' => 'HighEnd Blinds provides custom window-covering consultations, local manufacturing, and professional installation in Fort Saskatchewan. We serve residential and commercial spaces with solutions built to the dimensions and operating requirements of each window rather than trimmed-down, ready-made products.',
			'local' => 'Homes and workplaces in Fort Saskatchewan can require privacy, heat and glare management, bedroom darkness, or convenient control of tall glass. We match fabrics and mechanisms to those priorities, considering window direction, interior finishes, daily use, children and pets, and whether several shades should operate together.',
			'fit' => 'For offices, clinics, and customer-facing spaces, roller blinds provide a clean appearance and can be produced in matching fabric lots. In homes, zebra blinds, blackout rollers, sunscreen shades, and motorized options can be combined. Dream Curtains add soft light filtering and privacy at patio doors without being a blackout treatment.',
			'products' => "Fort Saskatchewan's mix of homes and workplaces means we're often solving different problems in the same week — zebra blinds and roller blinds in sunscreen, light-filtering, privacy, or blackout fabrics for residential privacy and glare control, motorized blinds for tall or hard-to-reach glass, and motorized Dream Curtains for patio doors and open family rooms. Operating options range from a simple wand or safety-guarded chain to a rechargeable motor with remote, app, schedule, or smart-home control, chosen to match how the space is actually used.",
			'process' => 'We start with a consultation at your Fort Saskatchewan home or workplace, measuring every window for width, height, depth, and mounting conditions before manufacturing the order at our Edmonton facility. Installation includes mounting and levelling hardware, checking clearances, testing every blind, and programming motorized units, with a full walkthrough of care and operation before we leave — whether the space is a single office or a full house.',
			'commercial' => 'For offices, clinics, and customer-facing spaces in Fort Saskatchewan, we produce matched fabric lots and consistent hardware so multi-window commercial orders look uniform, while residential projects get the same room-by-room attention regardless of size.',
			'care' => 'Because Fort Saskatchewan spaces range from busy customer-facing offices to quiet bedrooms, we recommend viewing samples in both direct and ambient light before deciding what each room actually needs. We\'ll walk through cleaning requirements, privacy expectations, and daily operation before you approve the order. Afterward, care stays simple: light dusting or a vacuum attachment, damp-cloth wiping for most roller fabrics, spot-cleaning only for zebra and curtain fabrics, and periodic recharging for anything motorized.',
		),
	);
}

function highend_render_service_city( $key ) {
	$data = highend_service_city_data();
	if ( ! isset( $data[ $key ] ) ) { return; }
	$c = $data[ $key ];
	$city = $c['city'];
	?>
	<section class="hb-city-hero">
		<div class="hb-wrap">
			<div class="eyebrow">Locally Made in Edmonton</div>
			<h1>Custom Blinds <?php echo esc_html( $city ); ?></h1>
			<p><?php echo esc_html( $c['intro'] ); ?></p>
			<div class="hb-city-actions"><a class="btn btn--primary" href="<?php echo esc_url( home_url( '/contact-us/' ) ); ?>">Book Free Consultation <?php highend_arrow(); ?></a><a class="btn btn--outline" href="tel:<?php echo esc_attr( preg_replace( '/[^0-9]/', '', HIGHEND_PHONE ) ); ?>">Call <?php echo esc_html( HIGHEND_PHONE ); ?></a></div>
		</div>
	</section>
	<article class="hb-city-content">
		<div class="hb-wrap">
			<h2>Window Coverings Selected for <?php echo esc_html( $city ); ?> Homes</h2>
			<p><?php echo esc_html( $c['local'] ); ?></p>
			<p><?php echo esc_html( $c['fit'] ); ?></p>

			<h2>Custom Blinds and Motorized Options</h2>
			<p><?php echo esc_html( $c['products'] ); ?> Learn more about our <a href="<?php echo esc_url( home_url( '/zebra-blinds/' ) ); ?>">zebra blinds</a>, <a href="<?php echo esc_url( home_url( '/roller-blinds/' ) ); ?>">roller blinds</a>, and <a href="<?php echo esc_url( home_url( '/motorized-blinds/' ) ); ?>">motorized blinds</a>.</p>

			<h2>Our Measurement, Manufacturing, and Installation Process</h2>
			<p><?php echo esc_html( $c['process'] ); ?></p>
			<p>Product and installation coverage is explained in our <a href="<?php echo esc_url( home_url( '/warranty/' ) ); ?>">warranty information</a>.</p>

			<h2>Residential and Commercial Projects</h2>
			<p><?php echo esc_html( $c['commercial'] ); ?></p>

			<h2>Choosing and Caring for Your New Blinds</h2>
			<p><?php echo esc_html( $c['care'] ); ?></p>

			<div class="hb-city-cta"><div><h2>Book a Free <?php echo esc_html( $city ); ?> Consultation</h2><p>Tell us what you need from the room—privacy, daylight, glare reduction, blackout, child safety, or motorized control—and we will bring suitable options.</p></div><a class="btn btn--primary" href="<?php echo esc_url( home_url( '/contact-us/' ) ); ?>">Get Free Estimate <?php highend_arrow(); ?></a></div>
			<nav class="hb-city-nav" aria-label="Service area navigation"><a href="<?php echo esc_url( home_url( '/service-areas/' ) ); ?>">All service areas</a><a href="<?php echo esc_url( home_url( '/gallery/' ) ); ?>">View installations</a><a href="<?php echo esc_url( home_url( '/about-us/' ) ); ?>">About our Edmonton factory</a></nav>
		</div>
	</article>
	<?php
}
